// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhQFxOcFSaYMOYVizCG9CRfUuLpxOyjpE',
    appId: '1:430783171502:web:4e1a665bb9e8800e17963f',
    messagingSenderId: '430783171502',
    projectId: 'morales-flutter-project',
    authDomain: 'morales-flutter-project.firebaseapp.com',
    databaseURL: 'https://morales-flutter-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'morales-flutter-project.firebasestorage.app',
    measurementId: 'G-M2FYD9NVCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2xnDsdv6PO1fkfxXPYDfuFh9P5HWX-e0',
    appId: '1:430783171502:android:42aa2243fd1345ff17963f',
    messagingSenderId: '430783171502',
    projectId: 'morales-flutter-project',
    databaseURL: 'https://morales-flutter-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'morales-flutter-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0MDkLOsnMC8U7u1ZEKYLd5izNGILVbaA',
    appId: '1:430783171502:ios:3485e94c5423fdb617963f',
    messagingSenderId: '430783171502',
    projectId: 'morales-flutter-project',
    databaseURL: 'https://morales-flutter-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'morales-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.tmFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0MDkLOsnMC8U7u1ZEKYLd5izNGILVbaA',
    appId: '1:430783171502:ios:3485e94c5423fdb617963f',
    messagingSenderId: '430783171502',
    projectId: 'morales-flutter-project',
    databaseURL: 'https://morales-flutter-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'morales-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.tmFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhQFxOcFSaYMOYVizCG9CRfUuLpxOyjpE',
    appId: '1:430783171502:web:8ed41bb6fbf5773e17963f',
    messagingSenderId: '430783171502',
    projectId: 'morales-flutter-project',
    authDomain: 'morales-flutter-project.firebaseapp.com',
    databaseURL: 'https://morales-flutter-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'morales-flutter-project.firebasestorage.app',
    measurementId: 'G-X6TQXQM189',
  );
}
